/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShiftIndexRouteImport } from './routes/shift/index'
import { Route as CharterIndexRouteImport } from './routes/charter/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftIndexRoute = ShiftIndexRouteImport.update({
  id: '/shift/',
  path: '/shift/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharterIndexRoute = CharterIndexRouteImport.update({
  id: '/charter/',
  path: '/charter/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/charter/': typeof CharterIndexRoute
  '/shift/': typeof ShiftIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charter': typeof CharterIndexRoute
  '/shift': typeof ShiftIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/charter/': typeof CharterIndexRoute
  '/shift/': typeof ShiftIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/charter/' | '/shift/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/charter' | '/shift'
  id: '__root__' | '/' | '/charter/' | '/shift/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharterIndexRoute: typeof CharterIndexRoute
  ShiftIndexRoute: typeof ShiftIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shift/': {
      id: '/shift/'
      path: '/shift'
      fullPath: '/shift/'
      preLoaderRoute: typeof ShiftIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charter/': {
      id: '/charter/'
      path: '/charter'
      fullPath: '/charter/'
      preLoaderRoute: typeof CharterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharterIndexRoute: CharterIndexRoute,
  ShiftIndexRoute: ShiftIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
